
###Create asma-ul-husna
POST localhost:8080/api/v1/asma-ul-husna/admin/create/ru
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ5MDU0ODEsInBob25lIjoiMTExIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2ODQ5OTE4ODEsImlzcyI6Ik11YXp6aW4ifQ._Qqt57VGplBP571fqR2d_Cq_GvYYhZCby4WLOyOdVcxMxbB673R8SL_dpUWH7eGrC16hqoTHsUV_YPu0Pr35vw
Content-Type:  application/json

{
  "arabicTitle": "RusArabic",
  "title": "RusTitle",
  "description": "RuDescription",
  "info": "RuInfo",
  "attachId": "e82a375c-21c6-4c73-9f25-459d7de818a0"
}

### Update asma-ul-husna
PUT localhost:8080/api/v1/asma-ul-husna/admin/update/ru/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ5MDU0ODEsInBob25lIjoiMTExIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2ODQ5OTE4ODEsImlzcyI6Ik11YXp6aW4ifQ._Qqt57VGplBP571fqR2d_Cq_GvYYhZCby4WLOyOdVcxMxbB673R8SL_dpUWH7eGrC16hqoTHsUV_YPu0Pr35vw
Content-Type:  application/json

{
  "arabicTitle": "RusArabic",
  "title": "RusTitle",
  "description": "RuDescription",
  "info": "RuInfo",
  "attachId": "e82a375c-21c6-4c73-9f25-459d7de818a0"
}


### Get asma-ul-husna
GET localhost:8080/api/v1/asma-ul-husna/user/get/uz/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ5MDU1NjIsInBob25lIjoiMTIzIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NDk5MTk2MiwiaXNzIjoiTXVhenppbiJ9.6C5fgWTpZvK9pHNcNNvrPgTXAw8MAXooJf1rYeyXxnHlAOAWBmy6xSxEBNFAoDAkYxqu25jw6qB3ztbZWY8hDw


### Get asma-ul-husna list
GET localhost:8080/api/v1/asma-ul-husna/user/get-list/ru
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ5MDU1NjIsInBob25lIjoiMTIzIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NDk5MTk2MiwiaXNzIjoiTXVhenppbiJ9.6C5fgWTpZvK9pHNcNNvrPgTXAw8MAXooJf1rYeyXxnHlAOAWBmy6xSxEBNFAoDAkYxqu25jw6qB3ztbZWY8hDw



